version: '3'
volumes:
  postgres_data:
  pgadmin_data:
      driver: local
networks:
  devnet:
    driver: bridge
services:
  postgres:
      image: postgres
      restart: always
      volumes:
        - ./postgres_data:/var/lib/postgresql/data
        - $PWD/postgres.conf:/etc/postgresql/postgresql.conf
      command: postgres -c config_file=/etc/postgresql/postgresql.conf
      environment:
        POSTGRES_DB: devopsdb
        POSTGRES_USER: devops
        POSTGRES_PASSWORD: Appiskey.123
        PGDATA: /data/postgres
        ALLOW_IP_RANGE: 0.0.0.0/0
      ports:
        - "${POSTGRES_PORT:-5432}:5432"
      networks:
        - devnet
  pgadmin:
      container_name: pgadmin_container
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-devops@gmail.com}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-Appiskey.123}
      volumes:
        - pgadmin_data:/root/.pgadmin
      ports:
        - "${PGADMIN_PORT:-5050}:80"
      networks:
        - devnet
      restart: unless-stopped
      depends_on:
        - postgres



